%make vrt and xml files
wraprate=50;
set_params


%make VRT file
fid=fopen(['ts4.unw.vrt'],'w');
fprintf(fid,['<VRTDataset rasterXSize="' num2str(newnx) '" rasterYSize="' num2str(newny) '4083">\n']);
fprintf(fid,['    <SRS>EPSG:4326</SRS>                                                      \n']);
fprintf(fid,['    <GeoTransform>1.5, 4.0, 0.0, 3.5, 0.0, 8.0</GeoTransform>                         \n']);
fprintf(fid,['    <VRTRasterBand band="1" dataType="Float32" subClass="VRTRawRasterBand">   \n']);
fprintf(fid,['        <SourceFilename relativeToVRT="1">filt_topophase.unw</SourceFilename> \n']);
fprintf(fid,['        <ByteOrder>LSB</ByteOrder>                                            \n']);
fprintf(fid,['        <ImageOffset>0</ImageOffset>                                          \n']);
fprintf(fid,['        <PixelOffset>8</PixelOffset>                                          \n']);
fprintf(fid,['        <LineOffset>' num2str(nx*2) '</LineOffset>                                        \n']);
fprintf(fid,['    </VRTRasterBand>                                                          \n']);
fprintf(fid,['    <VRTRasterBand band="2" dataType="Float32" subClass="VRTRawRasterBand">   \n']);
fprintf(fid,['        <SourceFilename relativeToVRT="1">filt_topophase.unw</SourceFilename> \n']);
fprintf(fid,['        <ByteOrder>LSB</ByteOrder>                                            \n']);
fprintf(fid,['        <ImageOffset>' num2str(nx) '</ImageOffset>                                      \n']);
fprintf(fid,['        <PixelOffset>8</PixelOffset>                                          \n']);
fprintf(fid,['        <LineOffset>' num2str(nx*2) '</LineOffset>                                        \n']);
fprintf(fid,['    </VRTRasterBand>                                                          \n']);
fprintf(fid,['</VRTDataset>                                                                 \n']);
fclose(fid);



%Make xml file
fid=fopen(['ts4.unw.xml'],'w');
fprintf(fid,['<imageFile>                                                                                             \n']);
fprintf(fid,['    <property name="ISCE_VERSION">                                                                      \n']);
fprintf(fid,['        <value>Release: 2.0.0_201609, svn-2145, 20160906. Current: svn-Unversioned directory.</value>   \n']);
fprintf(fid,['    </property>                                                                                         \n']);
fprintf(fid,['    <property name="access_mode">                                                                       \n']);
fprintf(fid,['        <value>read</value>                                                                             \n']);
fprintf(fid,['        <doc>Image access mode.</doc>                                                                   \n']);
fprintf(fid,['    </property>                                                                                         \n']);
fprintf(fid,['    <property name="byte_order">                                                                        \n']);
fprintf(fid,['        <value>l</value>                                                                                \n']);
fprintf(fid,['        <doc>Endianness of the image.</doc>                                                             \n']);
fprintf(fid,['    </property>                                                                                         \n']);
fprintf(fid,['    <component name="coordinate1">                                                                      \n']);
fprintf(fid,['        <factorymodule>isceobj.Image</factorymodule>                                                    \n']);
fprintf(fid,['        <factoryname>createCoordinate</factoryname>                                                     \n']);
fprintf(fid,['        <doc>First coordinate of a 2D image (width).</doc>                                              \n']);
fprintf(fid,['        <property name="delta">                                                                         \n']);
fprintf(fid,['            <value>1</value>                                                                            \n']);
fprintf(fid,['            <doc>Coordinate quantization.</doc>                                                         \n']);
fprintf(fid,['        </property>                                                                                     \n']);
fprintf(fid,['        <property name="endingvalue">                                                                   \n']);
fprintf(fid,['            <value>'  num2str(newnx) '</value>                                                                         \n']);
fprintf(fid,['            <doc>Starting value of the coordinate.</doc>                                                \n']);
fprintf(fid,['        </property>                                                                                     \n']);
fprintf(fid,['        <property name="family">                                                                        \n']);
fprintf(fid,['            <value>imagecoordinate</value>                                                              \n']);
fprintf(fid,['            <doc>Instance family name</doc>                                                             \n']);
fprintf(fid,['        </property>                                                                                     \n']);
fprintf(fid,['        <property name="name">                                                                          \n']);
fprintf(fid,['            <value>imagecoordinate_name</value>                                                         \n']);
fprintf(fid,['            <doc>Instance name</doc>                                                                    \n']);
fprintf(fid,['        </property>                                                                                     \n']);
fprintf(fid,['        <property name="size">                                                                          \n']);
fprintf(fid,['            <value>'  num2str(newnx) '</value>                                                                         \n']);
fprintf(fid,['            <doc>Coordinate size.</doc>                                                                 \n']);
fprintf(fid,['        </property>                                                                                     \n']);
fprintf(fid,['        <property name="startingvalue">                                                                 \n']);
fprintf(fid,['            <value>0</value>                                                                            \n']);
fprintf(fid,['            <doc>Starting value of the coordinate.</doc>                                                \n']);
fprintf(fid,['        </property>                                                                                     \n']);
fprintf(fid,['    </component>                                                                                        \n']);
fprintf(fid,['    <component name="coordinate2">                                                                      \n']);
fprintf(fid,['        <factorymodule>isceobj.Image</factorymodule>                                                    \n']);
fprintf(fid,['        <factoryname>createCoordinate</factoryname>                                                     \n']);
fprintf(fid,['        <doc>Second coordinate of a 2D image (length).</doc>                                            \n']);
fprintf(fid,['        <property name="delta">                                                                         \n']);
fprintf(fid,['            <value>1</value>                                                                            \n']);
fprintf(fid,['            <doc>Coordinate quantization.</doc>                                                         \n']);
fprintf(fid,['        </property>                                                                                     \n']);
fprintf(fid,['        <property name="endingvalue">                                                                   \n']);
fprintf(fid,['            <value>'  num2str(newny) '</value>                                                                         \n']);
fprintf(fid,['            <doc>Starting value of the coordinate.</doc>                                                \n']);
fprintf(fid,['        </property>                                                                                     \n']);
fprintf(fid,['        <property name="family">                                                                        \n']);
fprintf(fid,['            <value>imagecoordinate</value>                                                              \n']);
fprintf(fid,['            <doc>Instance family name</doc>                                                             \n']);
fprintf(fid,['        </property>                                                                                     \n']);
fprintf(fid,['        <property name="name">                                                                          \n']);
fprintf(fid,['            <value>imagecoordinate_name</value>                                                         \n']);
fprintf(fid,['            <doc>Instance name</doc>                                                                    \n']);
fprintf(fid,['        </property>                                                                                     \n']);
fprintf(fid,['        <property name="size">                                                                          \n']);
fprintf(fid,['            <value>'  num2str(newny) '</value>                                                                         \n']);
fprintf(fid,['            <doc>Coordinate size.</doc>                                                                 \n']);
fprintf(fid,['        </property>                                                                                     \n']);
fprintf(fid,['        <property name="startingvalue">                                                                 \n']);
fprintf(fid,['            <value>0</value>                                                                            \n']);
fprintf(fid,['            <doc>Starting value of the coordinate.</doc>                                                \n']);
fprintf(fid,['        </property>                                                                                     \n']);
fprintf(fid,['    </component>                                                                                        \n']);
fprintf(fid,['    <property name="data_type">                                                                         \n']);
fprintf(fid,['        <value>float</value>                                                                            \n']);
fprintf(fid,['        <doc>Image data type.</doc>                                                                     \n']);
fprintf(fid,['    </property>                                                                                         \n']);
fprintf(fid,['    <property name="extra_file_name">                                                                   \n']);
fprintf(fid,['        <value>rates_4.vrt</value>                                                    \n']);
fprintf(fid,['        <doc>For example name of vrt metadata.</doc>                                                    \n']);
fprintf(fid,['    </property>                                                                                         \n']);
fprintf(fid,['    <property name="family">                                                                            \n']);
fprintf(fid,['        <value>unwimage</value>                                                                         \n']);
fprintf(fid,['        <doc>Instance family name</doc>                                                                 \n']);
fprintf(fid,['    </property>                                                                                         \n']);
fprintf(fid,['    <property name="file_name">                                                                         \n']);
fprintf(fid,['        <value>merged/filt_topophase.unw</value>                                                        \n']);
fprintf(fid,['        <doc>Name of the image file.</doc>                                                              \n']);
fprintf(fid,['    </property>                                                                                         \n']);
fprintf(fid,['    <property name="image_type">                                                                        \n']);
fprintf(fid,['        <value>unw</value>                                                                              \n']);
fprintf(fid,['        <doc>Image type used for displaying.</doc>                                                      \n']);
fprintf(fid,['    </property>                                                                                         \n']);
fprintf(fid,['    <property name="length">                                                                            \n']);
fprintf(fid,['        <value>'  num2str(newny) '</value>                                                                             \n']);
fprintf(fid,['        <doc>Image length</doc>                                                                         \n']);
fprintf(fid,['    </property>                                                                                         \n']);
fprintf(fid,['    <property name="name">                                                                              \n']);
fprintf(fid,['        <value>unwimage_name</value>                                                                    \n']);
fprintf(fid,['        <doc>Instance name</doc>                                                                        \n']);
fprintf(fid,['    </property>                                                                                         \n']);
fprintf(fid,['    <property name="number_bands">                                                                      \n']);
fprintf(fid,['        <value>2</value>                                                                                \n']);
fprintf(fid,['        <doc>Number of image bands.</doc>                                                               \n']);
fprintf(fid,['    </property>                                                                                         \n']);
fprintf(fid,['    <property name="scheme">                                                                            \n']);
fprintf(fid,['        <value>BIL</value>                                                                              \n']);
fprintf(fid,['        <doc>Interleaving scheme of the image.</doc>                                                    \n']);
fprintf(fid,['    </property>                                                                                         \n']);
fprintf(fid,['    <property name="width">                                                                             \n']);
fprintf(fid,['        <value>'  num2str(newnx) '</value>                                                                             \n']);
fprintf(fid,['        <doc>Image width</doc>                                                                          \n']);
fprintf(fid,['    </property>                                                                                         \n']);
fprintf(fid,['    <property name="xmax">                                                                              \n']);
fprintf(fid,['        <value>'  num2str(newnx) '</value>                                                                             \n']);
fprintf(fid,['        <doc>Maximum range value</doc>                                                                  \n']);
fprintf(fid,['    </property>                                                                                         \n']);
fprintf(fid,['    <property name="xmin">                                                                              \n']);
fprintf(fid,['        <value>0</value>                                                                                \n']);
fprintf(fid,['        <doc>Minimum range value</doc>                                                                  \n']);
fprintf(fid,['    </property>                                                                                         \n']);
fprintf(fid,['</imageFile>                                                                                            \n']);
    system(['fixImageXml.py -i ts4.unw -f']);
 fclose(fid)
 
%Geocode and make kml
% bounds=num2str([floor(min([frames.lat])-.5) ceil(max([frames.lat])+.5) floor(min([frames.lon])-.5) ceil(max([frames.lon])+.5)]);
bounds=[34 37 -121 -118];
dates(id).dir='int_150706_150612'
system(['geocode.py -d final_dem -m ' dates(id).dir ' -b ' bounds ' -i ts4.unw -r ' num2str(rlooks) ' -a ' num2str(alooks)]);
system(['mdx.py ts4.unw.geo -kml ts4.kml -wrap ' num2str(wraprate) ' -cmap cmy']);

